package command.search;

import com.fasterxml.jackson.databind.node.ObjectNode;
import enums.*;
import fileio.CommandInput;
import fileio.FilterInput;
import fileio.OutputFormatter;
import fileio.SearchedTicketDTO;
import main.BugTrackerSystem;
import milestone.Milestone;
import ticket.Ticket;
import user.Developer;
import user.Manager;
import user.User;
import user.UserDatabase;

import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class ManagerSearchStrategy implements SearchStrategy {

    @Override
    public void executeSearch(final BugTrackerSystem system, final List<ObjectNode> outputs,
                              final User user, final CommandInput input) {

        FilterInput filters = input.getFilters();
        if (!user.getRole().equals(Role.MANAGER)) {
            return;
        }
        Manager manager = (Manager) user;
        if (filters.getSearchType().equals("DEVELOPER")) {
            searchDevelopers(system, outputs, manager, input);
        } else {
            searchTickets(system, outputs, user, input);
        }
    }

    private void searchDevelopers(final BugTrackerSystem system, final List<ObjectNode> outputs,
                                  final Manager manager, CommandInput input) {
        FilterInput filters = input.getFilters();
        Map<String, User> users = system.getUserDatabase().getUsers();

        ArrayList<Developer> developers = new ArrayList<>();

//        for (Map.Entry<String, User> userEntry : users.entrySet()) {
//            User user = userEntry.getValue();
//            String username = userEntry.getKey();
//            if (user.getRole().equals(Role.DEVELOPER) && manager.getSubordinates().contains(username)) {
//                developers.add((Developer) user);
//            }
//        }

        if (manager.getSubordinates() != null) {
            for (String username : manager.getSubordinates()) {
                User subord = users.get(username);
                if (subord == null) {
                    continue;
                }
                if (subord.getRole().equals(Role.DEVELOPER)) {
                    developers.add((Developer) subord);
                }

            }
        }

        Stream<Developer> devStream = getDeveloperStream(developers, filters);

        List<Developer> results = devStream
                .sorted(Comparator.comparing(Developer::getUsername))
                .collect(Collectors.toList());

        outputs.add(OutputFormatter.createSearchResponse(
                input.getCommand(),
                manager.getUsername(),
                input.getTimestamp(),
                input.getFilters().getSearchType(),
                results
        ));
    }

    /**
     * Static method generated by Intellij to modularize the code
     * Streaming is static and done separately from the main logic
     * @param developers
     * @param filters
     * @return
     */
    private static Stream<Developer> getDeveloperStream( ArrayList<Developer> developers, final FilterInput filters) {
        Stream<Developer> devStream = developers.stream();
        if (filters.getExpertiseArea() != null) {
            devStream = devStream.filter(dev -> dev.getExpertiseArea().name().equals(filters.getExpertiseArea()));
        }

        if (filters.getSeniority() != null) {
            devStream = devStream.filter(dev -> dev.getSeniority().name().equals(filters.getSeniority()));
        }

        if (filters.getPerformanceScoreAbove() != null) {
            devStream = devStream.filter(dev -> dev.getPerformanceScore() >= filters.getPerformanceScoreAbove());
        }

        if (filters.getPerformanceScoreBelow() != null) {
            devStream = devStream.filter(dev -> dev.getPerformanceScore() <= filters.getPerformanceScoreBelow());
        }
        return devStream;
    }

    /**
     * Method that searches tickets by filtering the stream with predicates
     * Adds the node containing the matching keyowrds to the output
     * @param system
     * @param outputs
     * @param user
     * @param input
     */
    private void searchTickets(final BugTrackerSystem system, final List<ObjectNode> outputs,
                               final User user, final CommandInput input) {
        FilterInput filter = input.getFilters();
        List<Ticket> allTickets = system.getTicketDatabase().getTickets();
        Stream<Ticket> ticketStream = allTickets.stream();

        if (filter.getBusinessPriority() != null) {
            ticketStream = ticketStream.filter(ticket ->
                    ticket.getBusinessPriority().name().equals(filter.getBusinessPriority()));
        }

        if (filter.getType() != null) {
            ticketStream = ticketStream.filter(ticket -> ticket.getType().name().equals(filter.getType()));
        }

        if (filter.getCreatedAt() != null) {
            LocalDate filterCreatedAt = LocalDate.parse(filter.getCreatedAt());
            ticketStream = ticketStream.filter(ticket -> ticket.getReportedTimestamp().equals(filterCreatedAt));
        }

        if (filter.getCreatedBefore() != null) {
            LocalDate filterCreatedBefore = LocalDate.parse(filter.getCreatedBefore());
            ticketStream = ticketStream.filter(ticket -> ticket.getReportedTimestamp().isBefore(filterCreatedBefore));
        }

        if (filter.getCreatedAfter() != null) {
            LocalDate filterCreatedAfter = LocalDate.parse(filter.getCreatedAfter());
            ticketStream = ticketStream.filter(ticket -> ticket.getReportedTimestamp().isAfter(filterCreatedAfter));
        }

        if (filter.isAvailableForAssignment()) {
            ticketStream = ticketStream.filter(ticket -> isTicketAvailForAssignment(system, ticket, user));
        }

        // KEYWORDS
        boolean searchesKeywords =  filter.getKeywords() != null && !filter.getKeywords().isEmpty();
        if (searchesKeywords) {
            ticketStream = ticketStream.filter(ticket -> containsKeywords(ticket, filter.getKeywords()));
        }

        // SORT
        List<Ticket> sortedTickets = ticketStream
                .sorted(Comparator.comparing(Ticket::getReportedTimestamp).thenComparing(Ticket::getId))
                .toList();

        // OBJECT
        List<ObjectNode> jsonOutput = new ArrayList<>();

        for (Ticket ticket : sortedTickets) {
            SearchedTicketDTO dto = new SearchedTicketDTO(ticket);
            ObjectNode node = (ObjectNode) OutputFormatter.mapToNode(dto);
            List<String> matches = new ArrayList<>();
            if (searchesKeywords) {
                matches = getMatches(ticket, filter.getKeywords());
            }
            node.set("matchingWords", OutputFormatter.mapToNode(matches));
            jsonOutput.add(node);
        }



        outputs.add(OutputFormatter.createSearchResponse(
                input.getCommand(),
                user.getUsername(),
                input.getTimestamp(),
                filter.getSearchType(),
                jsonOutput
        ));

    }


    /**
     * Returns true if ticket is avail for assignment(checks the 5 rules at assignTicket)
     * and false otherwise
     * @param system
     * @param ticket
     * @param user
     * @return
     */
    private boolean isTicketAvailForAssignment(final BugTrackerSystem system, final Ticket ticket, final User user) {
        Developer developer = (Developer) user;

        // Seniority check
        Seniority seniority = developer.getSeniority();
        BusinessPriority businessPriority = ticket.getBusinessPriority();
        TicketType ticketType = ticket.getType();

        if (!seniority.hasAccessToPriority(businessPriority)) {
            return false;
        }
        if (!seniority.hasAccessToTicketType(ticketType)) {
            return false;
        }

        // Expertise check
        ExpertiseArea devExpertise = developer.getExpertiseArea();
        String ticketZone = ticket.getExpertiseArea().name();
        if (!devExpertise.hasAccessToZone(ticketZone)) {
            return false;
        }

        // Ticket status check
        if (ticket.getStatus() != Status.OPEN) {
            return false;
        }

        // Milestone did not assign developer
        Milestone ownerMilestone = system.getMilestoneDatabase().getMilestoneByTicketId(ticket.getId());
        if (ownerMilestone == null || ownerMilestone.getAssignedDevs() == null ){
            return false;
        }
        if (!ownerMilestone.getAssignedDevs().contains(developer.getUsername())) {
            return false;
        }
        // Milestone is blocked
        if (ownerMilestone.isBlocked()) {
            return false;
        }

        return true;
    }

    /**
     * Keyowrds looks for partial or complete matches of at least a word
     * from description or title
     * @param ticket
     * @param keywords
     * @return
     */
    private boolean containsKeywords(Ticket ticket, ArrayList<String> keywords) {
        String content = (ticket.getTitle() + " " + ticket.getDescription()).toLowerCase();
        for (String k : keywords) {
            if (content.contains(k.toLowerCase()))  {
                return true;
            }
        }
        return false;
    }

    /**
     * Returns the list of matching words sorted lexicographically
     * @param ticket
     * @param keywords
     * @return
     */
    private List<String> getMatches(Ticket ticket, ArrayList<String> keywords) {
        String content = (ticket.getTitle() + " " + ticket.getDescription()).toLowerCase();
        List<String> matches = new ArrayList<>();
        for (String keyword : keywords) {
            if (content.contains(keyword.toLowerCase())) {
                matches.add(keyword.toLowerCase());
            }
        }
        Collections.sort(matches);
        return matches;
    }
}
